MyBook/Models/Admin/EditAuthorViewModel.cs
using MyBook.Entities;
using System.ComponentModel.DataAnnotations;

namespace MyBook.Models.Admin
{
    public class EditAuthorViewModel
    {
        const string letters = @"^([A-Za-z]|[А-Яа-яё])+((\s)?((\'|\-|\.)?([A-Za-z]|[А-Яа-яё])+))*$";
        const string url = @"^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$";
        public int? AuthorId { get; set; }
        [Required(ErrorMessage = "Введите имя автора")]
        [MaxLength(50, ErrorMessage = "Длина имени не должна превышать 50 символов"), MinLength(5, ErrorMessage = "Длина имени не должна быть меньше 5 символов")]
        [RegularExpression(letters, ErrorMessage = "Введите корректное имя", MatchTimeoutInMilliseconds = 10)]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Введите корректную дату рождения")]
        public DateTime? BirthDate { get; set; } = null;

        [DataType(DataType.Url)]
        [RegularExpression(url, ErrorMessage = "Введите корректный url")]
        public string? ImageLink { get; set; } = null;
    }
}

MyBook/Models/Admin/EditBookViewModel.cs
using MyBook.Entities;
using System.ComponentModel.DataAnnotations;

namespace MyBook.Models.Admin
{
    public class EditBookViewModel
    {
        const string text = @"^([А-Я]|[а-яё]|[A-z]|[A-z]|\s|\d|[.,!?:;-])*";
        const string price = @"^((\d{1,3}|\s*){1})((\,\d{3}|\d)*)(\s*|\.(\d{2}))$";
        const string url = @"^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$";
        public int? BookId { get; set; }

        [Required(ErrorMessage = "Введите название")]
        [MaxLength(50, ErrorMessage = "Длина названия не должна превышать 50 символов"), MinLength(5, ErrorMessage = "Длина названия не должна быть меньше 5 символов")]
        [RegularExpression(text, ErrorMessage = "Введите корректное название", MatchTimeoutInMilliseconds = 10)]
        [DataType(DataType.Text)]
        public string Name { get; set; } = null!;

        [Required(ErrorMessage = "Выберите язык")]
        public string Language { get; set; } = null!;
        [DataType(DataType.Date, ErrorMessage = "Введите корректную дату рождения")]
        public string? PublishedDate { get; set; }
        [Required(ErrorMessage = "Выберите является ли книга 18+")]
        public bool IsForAdult { get; set; }
        [Required(ErrorMessage = "Выберите платная ли книга")]
        public bool IsPaid { get; set; }
        [Required(ErrorMessage = "Выберите жанр")]
        public string? GenreName { get; set; }
        [Required(ErrorMessage = "Выберите автора")]
        public string? AuthorName { get; set; }

        [Required(ErrorMessage = "Введите кол-во страниц в книге")]
        public int? PagesCount { get; set; }
        [RegularExpression(price, ErrorMessage = "Введите корректную цену")]
        [DataType(DataType.Currency)]
        public string? Price { get; set; }
        [Required(ErrorMessage = "Введите описание")]
        [DataType(DataType.MultilineText)]
        [RegularExpression(text, ErrorMessage = "Пожалуйста, используйте только русские буквы,цифры и знаки препинания")]
        [MaxLength(10000, ErrorMessage = "Длина описания не должна превышать 10000 символов"), MinLength(5, ErrorMessage = "Длина описания не должна быть меньше 10 символов")]
        public string? Description { get; set; }
        [DataType(DataType.Url)]
        [RegularExpression(url, ErrorMessage = "Введите корректный url")]
        public string? UrlEPUB { get; set; } = null!;
        [DataType(DataType.Url)]
        [RegularExpression(url, ErrorMessage = "Введите корректный url")]
        public string? UrlPDF { get; set; } = null!;
        [DataType(DataType.Url)]
        [RegularExpression(url, ErrorMessage = "Введите корректный url")]
        public string? ImageLink { get; set; } = null;

        public List<Author> Authors { get; set; } = new List<Author>();
        public List<Genre> Genres { get; set; } = new List<Genre>();
    }
}

MyBook/Models/Admin/EditUserViewModel.cs
using MyBook.Entities;
using System.ComponentModel.DataAnnotations;
using Type = MyBook.Entities.Type;

namespace MyBook.Models.Admin
{
    public class EditUserViewModel
    {
        public List<Type> SubscrTypes { get; set; } = new List<Type>();
        public List<Author> Authors { get; set; } = new List<Author>();
        public List<Genre> Genres { get; set; } = new List<Genre>();
        public string UserID { get; set; }
        public string? GenreName { get; set; }
        public string? AuthorName { get; set; }
        [Required(ErrorMessage = "Выберите период")]
        public int? Period { get; set; } = null;
        [Required(ErrorMessage = "Выберите тип подписки")]
        public int? TypeId { get; set; } = null;
    }
}

MyBook/Controllers/AdminProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBook.Entities;
using MyBook.Infrastructure.Repositories;
using MyBook.Models;
using MyBook.Models.Admin;
using Repositories;
using System.Security.Claims;
using Type = MyBook.Entities.Type;
namespace MyBook.Controllers
{
    /*[Authorize(Policy = "AdminsOnly")]*/
    public class AdminProfileController : Controller
    {
        private readonly IGenericRepository<Type> _typeRepository;
        private readonly EfAuthorRepository _authorRepository;
        private readonly EFGenreRepository _genreRepository;
        private readonly EfBookRepository _bookRepository;
        private readonly EFBookCenterRepository _bookCenterRepository;
        private readonly EFUserRepository _userRepository;
        private readonly EFUserSubscrRepository _userSubscrRepository;
        private readonly IGenericRepository<Object> _genericRepository;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public AdminProfileController(IGenericRepository<Type> typeRep,
        EfAuthorRepository authorRepository,
        EFGenreRepository genreRepository,
            EfBookRepository bookRepository,
             EFBookCenterRepository bookCenterRepository,
            EFUserRepository userRepository,
            IGenericRepository<object> genericRepository,
            EFUserSubscrRepository userSubscrRepository,
        SignInManager<User> signInManager,
        UserManager<User> userManager)
        {
            _typeRepository = typeRep;
            _authorRepository = authorRepository;
            _bookRepository = bookRepository;
            _bookCenterRepository = bookCenterRepository;
            _genericRepository = genericRepository;
            _userRepository = userRepository;
            _signInManager = signInManager;
            _userSubscrRepository = userSubscrRepository;
            _genreRepository = genreRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(new AdminViewModel
            {
                Authors = GetAuthors(),
                Books = GetBooks(),
                Centers = GetCenters(),
                SubscrTypes = GetTypes(),
                Users = await GetUsers()
            });
        }

        public async Task<IActionResult> ShowCurrent(string page)
        {
            return View("Index", new AdminViewModel
            {
                Authors = GetAuthors(),
                Books = GetBooks(),
                Centers = GetCenters(),
                SubscrTypes = GetTypes(),
                Users = await GetUsers(),
                CurrentPage = page
            });
        }
        #region SubscrType
        public async Task<IActionResult> DeleteSubscrType(Type type)
        {
            await _typeRepository.Remove(type);
            var page = "Subscription";
            return RedirectToAction("ShowCurrent", new { page });
        }

        public IActionResult EditSubscriptionModal(EditSubscrViewModel model)
        {
            return View(model);
        }

        public IActionResult AddSubscriptionModal(EditSubscrViewModel model)
        {
            return View(model);
        }

        public async Task<IActionResult> AddSubscrType(EditSubscrViewModel model)
        {
            if (ModelState.IsValid)
            {
                var type = new Type { Description = model.Description, Price = model.Price, TypeName = model.TypeName };
                await _typeRepository.Create(type);
                var page = "Subscription";
                return RedirectToAction("ShowCurrent", new { page });
            }
            return View("AddSubscriptionModal", model);
        }

        public async Task<IActionResult> EditSubscrType(EditSubscrViewModel model)
        {
            if (ModelState.IsValid && model.TypeId != null)
            {
                var type = await _typeRepository.FindById((int)model.TypeId);
                if (type == null)
                {
                    ModelState.AddModelError("TypeNotFound", "Тип с таким айди не был найден");
                    return View("EditSubscriptionModal", model);
                }
                type.Description = model.Description;
                type.Price = model.Price;
                type.TypeName = model.TypeName;
                await _typeRepository.Update(type, null);
                var page = "Subscription";
                return RedirectToAction("ShowCurrent", new { page });
            }
            return View("EditSubscriptionModal", model);
        }

        #endregion

        #region Author
        //TODO search author
        public async Task<IActionResult> DeleteAuthor(Author author)
        {
            await _authorRepository.Remove(author);
            var page = "Author";
            return RedirectToAction("ShowCurrent", new { page });
        }
        public IActionResult EditAuthorModal(EditAuthorViewModel model)
        {
            return View(model);
        }

        public IActionResult AddAuthorModal(EditAuthorViewModel model)
        {
            return View(model);
        }

        public async Task<IActionResult> AddAuthor(EditAuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var author = new Author { Name = model.Name, BirthDate = model.BirthDate?.ToShortDateString(), ImgLinks = new List<ImgLink>() };
                if (model.ImageLink != null)
                {
                    var imageLink = new ImgLink { AuthorId = author.AuthorId, Url = model.ImageLink };
                    author.ImgLinks.Add(imageLink);
                    await _genericRepository.CreateAll(new List<object>() { author, imageLink });
                }
                else await _authorRepository.Create(author);
                var page = "Author";
                return RedirectToAction("ShowCurrent", new { page });
            }
            return View("AddAuthorModal", model);
        }

        public async Task<IActionResult> EditAuthor(EditAuthorViewModel model)
        {
            if (ModelState.IsValid && model.AuthorId != null)
            {
                var author = await _authorRepository.FindById((int)model.AuthorId);
                if (author == null)
                {
                    ModelState.AddModelError("AuthorNotFound", "Автор с таким айди не был найден");
                    return View("EditAuthorModal", model);
                }
                author.Name = model.Name;
                if (model.BirthDate != null)
                    author.BirthDate = model.BirthDate?.ToShortDateString();
                if (model.ImageLink != null)
                {
                    var imageLink = new ImgLink { AuthorId = author.AuthorId, Url = model.ImageLink };
                    await _genericRepository.CreateAll(new List<object>() { imageLink });
                    author.ImgLinks = new List<ImgLink> { imageLink };
                }
                await _authorRepository.Update(author, null);
                var page = "Author";
                return RedirectToAction("ShowCurrent", new { page });
            }
            return View("EditAuthorModal", model);
        }

        #endregion

        #region Book
        //TODO search book
        public async Task<IActionResult> DeleteBook(Book book)
        {
            //TODO fix with other links
            await _bookRepository.Remove(book);
            var page = "Book";
            return RedirectToAction("Index", new { page });
        }

        public IActionResult EditBookModal(EditBookViewModel model)
        {
            model.Genres = GetGenres();
            model.Authors = GetAuthors();
            return View(model);
        }

        public IActionResult AddBookModal()
        {
            var model = new MyBook.Models.Admin.EditBookViewModel { Genres = GetGenres(), Authors = GetAuthors() };
            return View(model);
        }

        public async Task<IActionResult> AddBook(EditBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var book = new Book { Name = model.Name, ImgLinks = new List<ImgLink>(), IsForAdult = model.IsForAdult, IsPaid = model.IsPaid, PublishedDate = model.PublishedDate, Language = model.Language };
                var entities = new List<object>();
                if (model.GenreName != null)
                {
                    var genreId = _genreRepository.Get(it => it.Name == model.GenreName).FirstOrDefault()?.GenreId;
                    if (genreId != null)
                    {
                        var bookGenre = new BookGenre { Book = book, GenreId = (int)genreId };
                        entities.Add(bookGenre);
                        book.BookGenres.Add(bookGenre);
                    }
                }
                if (model.AuthorName != null)
                {
                    var authorId = _authorRepository.Get(it => it.Name == model.AuthorName).FirstOrDefault()?.AuthorId;
                    if (authorId != null)
                    {
                        var bookAuthor = new AuthorBook { Book = book, AuthorId = (int)authorId };
                        book.AuthorBooks.Add(bookAuthor);
                        entities.Add(bookAuthor);
                    }
                }
                var desc = new BookDesc { Description = model.Description, DownloadLinks = new List<DownloadLink>(), PagesCount = model.PagesCount != null ? (int)model.PagesCount : 0, Price = model.Price, Book = book };
                book.Description = desc;
                if (model.ImageLink != null)
                {
                    var imageLink = new ImgLink { Book = book, Url = model.ImageLink };
                    book.ImgLinks.Add(imageLink);

MyBook/Views/AdminProfile/AddAuthorModal.cshtml
@model MyBook.Models.Admin.EditAuthorViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["AddAuthor"] - MyBook</title>
</head>
<body class="lock">
    <section class="modal_wrapper">
        <div class="modal_admin">
            <div class="modal-header">
                <h2 class="modal-title" id="exampleModalLongTitle">Добавить автора</h2>
                <button class="close_modal">
                    <a class="nav-link" asp-controller="AdminProfile" asp-action="ShowCurrent" asp-route-page="Author">
                        <img src="/assets/img/close.svg">
                    </a>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="AddAuthor" asp-controller="AdminProfile">
                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="AuthorId" id="authorId" />
                    <div class="form-group">
                        <label asp-for="Name" for="nameInput">Имя автора</label>
                        <input asp-for="Name" type="text" class="form-control" id="nameInput" placeholder="Имя">
                        <span class="alerts" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BirthDate">Дата рождения: </label><br />
                        <input asp-for="BirthDate" class="form-control" type="date" id="datepicker" max="2020-04-30">
                        <span class="alerts" asp-validation-for="BirthDate"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageLink" for="img">Ссылка на изображение</label>
                        <input asp-for="ImageLink" type="text" class="form-control" id="img" placeholder="Ссылка на изображение" />
                        <span class="alerts" asp-validation-for="ImageLink"></span>
                    </div>
                    <div class="form-button">
                        <button type="submit" class="btn btn-warning">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</body>
</html>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
    }

MyBook/Views/AdminProfile/AddBookCenterModal.cshtml
@model MyBook.Models.Admin.EditCenterViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["AddBookCenter"] - MyBook</title>
</head>
<body class="lock">
    <section class="modal_wrapper">
        <div class="main_content_page">
            aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal_admin">
                    <div class="modal-header">
                        <h2 class="modal-title" id="exampleModalLongTitle">Добавить магазин</h2>
                        <button class="close_modal">
                            <a class="nav-link" asp-controller="AdminProfile" asp-action="ShowCurrent" asp-route-page="BookCenter">
                                <img src="/assets/img/close.svg">
                            </a>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="AddBookCenter" asp-controller="AdminProfile">
                            <input type="hidden" asp-for=BookCenterId id="bookCenterId">
                            <div class="form-group">
                                <label asp-for=Name for="nameInput">Название магазина</label>
                                <input asp-for=Name type="text" class="form-control" id="nameInput" placeholder="Название магазина">
                                <span class="alerts" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for=Address for="nameInput">Адрес</label>
                                <input asp-for=Address type="text" class="form-control" id="addressInput" placeholder="Адрес">
                                <span class="alerts" asp-validation-for="Address"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for=Phone for="nameInput">Телефоны</label>
                                <input asp-for=Phone type="text" class="form-control" id="phoneInput" placeholder="Телефон">
                                <span class="alerts" asp-validation-for="Phone"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for=Description for="descInput">Описание</label>
                                <textarea asp-for=Description type="text" class="form-control" id="descInput" placeholder="Описание"></textarea>
                                <span class="alerts" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-button">
                                <button type="submit" class="btn btn-warning">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
    }

MyBook/Views/AdminProfile/AddBookModal.cshtml
@model MyBook.Models.Admin.EditBookViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["AddBook"] - MyBook</title>
</head>
<body class="lock">
    <section class="modal_wrapper">
        <div class="main_content_page" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="" role="document">
                <div class="modal_admin_book">
                    <div class="modal-header">
                        <h2 class="modal-title" id="exampleModalLongTitle">Добавить книгу</h2>
                        <button class="close_modal">
                            <a class="nav-link" asp-controller="AdminProfile" asp-action="ShowCurrent" asp-route-page="Book">
                                <img src="/assets/img/close.svg">
                            </a>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="AddBook" asp-controller="AdminProfile">
                            <div class="d-flex">
                                <div class="left">
                                    <div asp-validation-summary="ModelOnly"></div>
                                    <input type="hidden" asp-for="BookId" id="bookId" />
                                    <div class="form-group">
                                        <label asp-for="Name" for="nameInput">Название книги</label>
                                        <input asp-for="Name" type="text" class="form-control" id="nameInput" placeholder="Название">
                                         <span class="alerts" asp-validation-for="Name"></span>
                                    </div>
                                    <label asp-for="Language" for="LanguageRadio">Язык</label>
                                    <div id="LanguageRadio">
                                        <div class="form-check form-check-inline">
                                            <input asp-for="Language" class="form-check-input" type="radio" value="ru">
                                            <p class="form-check-label" asp-for="Language">ru</p>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input asp-for="Language" class="form-check-input" type="radio" value="en">
                                            <p class="form-check-label" asp-for="Language">en</p>
                                        </div>
                                        <span class="alerts" asp-validation-for="Language"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="PublishedDate">Дата публикации: </label><br />
                                        <input asp-for="PublishedDate" class="form-control" type="date" min="1922-04-01" max="2020-04-30" id="datepicker">
                                        <span class="alerts" asp-validation-for="PublishedDate"></span>
                                    </div>
                                    <label asp-for="IsPaid" for="isPaid">Бесплатная ?</label>
                                    <div id="isPaid">
                                        <div class="form-check form-check-inline">
                                            <input asp-for="IsPaid" class="form-check-input" type="radio" value=@true>
                                            <p class="form-check-label" asp-for="IsPaid">Да</p>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input asp-for="IsPaid" class="form-check-input" type="radio" value=@false>
                                            <p class="form-check-label" asp-for="IsPaid">Нет</p>
                                        </div>
                                    </div>
                                    <label asp-for="IsForAdult" for="forAdult">Только для совершеннолтених ?</label>
                                    <div id="forAdult">
                                        <div class="form-check form-check-inline">
                                            <input asp-for="IsForAdult" class="form-check-input" type="radio" value=@true>
                                            <p class="form-check-label" asp-for="IsForAdult">Да</p>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input asp-for="IsForAdult" class="form-check-input" type="radio" value=@false>
                                            <p class="form-check-label" asp-for="IsForAdult">Нет</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Description" for="descInput">Описание книги</label>
                                        <textarea asp-for="Description" type="text" class="form-control" id="descInput" placeholder="Описание книги"></textarea>
                                         <span class="alerts" asp-validation-for="Description"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="PagesCount" for="pageCountInput">Количество страниц</label>
                                        <input asp-for="PagesCount" type="number" class="form-control" id="pageCountInput" placeholder="Кол-во страниц" />
                                        <span class="alerts" asp-validation-for="PagesCount"></span>
                                    </div>
                                </div>
                                <div class="right">
                                    <div class="form-group">
                                        <label asp-for="Price" for="priceInput">Цена</label>
                                        <input asp-for="Price" class="form-control" id="priceInput" placeholder="Стоимость">
                                         <span class="alerts" asp-validation-for="Price"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="UrlPDF" for="pdf">Ссылка на книгу (pdf)</label>
                                        <input asp-for="UrlPDF" type="text" class="form-control" id="pdf" placeholder="Ссылка на pdf" />
                                        <span class="alerts" asp-validation-for="UrlPDF"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="UrlEPUB" for="epub">Ссылка на книгу (epub)</label>
                                        <input asp-for="UrlEPUB" type="text" class="form-control" id="epub" placeholder="Ссылка на epub" />
                                         <span class="alerts" asp-validation-for="UrlEPUB"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="ImageLink" for="img">Ссылка на изображение</label>
                                        <input asp-for="ImageLink" type="text" class="form-control" id="img" placeholder="Ссылка на изображение" />
                                        <span class="alerts" asp-validation-for="ImageLink"></span>
                                    </div>
                                    <div class="form-group">
                                        <label>Выберите автора: </label>
                                        <input list="author-list" class="form-control" asp-for="AuthorName" id="author-input">
                                        <datalist id="author-list">
                                            @foreach (var author in Model.Authors)
                                            {
                                                <option value="@author.Name"></option>
                                            }
                                        </datalist>
                                         <span class="alerts" asp-validation-for="AuthorName"></span>
                                    </div>
                                    <div class="form-group">
                                        <label>Выберите жанр: </label>
                                        <input list="genre-list" class="form-control" asp-for="GenreName" id="genre-input">
                                        <datalist id="genre-list">
                                            @foreach (var genre in Model.Genres)
                                            {
                                                <option value="@genre.Name"></option>
                                            }
                                        </datalist>
                                        <span class="alerts" asp-validation-for="GenreName"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-button">
                                <button type="submit" class="btn btn-warning">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
    }

MyBook/Views/AdminProfile/_EditAuthor.cshtml
@model MyBook.Models.Admin.AdminViewModel
<section class="admin_functional">
    <h2>Получить информацию об авторе</h2>
    <div class="d-flex">
        <input class="form-control mr-sm-2" id="searchString" onchange="searchEditAuthor()" type="search" placeholder="Найти автора" aria-label="Search">
        <button class="btn-warning btn_spec" type="button" onclick="location.href='@Url.Action("AddAuthorModal", "AdminProfile", new MyBook.Models.Admin.EditAuthorViewModel())'">
            Добавить автора
        </button>
    </div>
    <div class="author_information authors_collection_grid">
        @foreach (var author in Model.Authors.Take(10))
        {
            @await Component.InvokeAsync("EditAuthor", author)
        }
    </div>
    <div class="container text-center">
        <button class="more" type="button" onclick="showMoreEditAuthors()">
            Показать ещё...
        </button>
    </div>
    <div class="add_author">
    </div>
</section>
<script src="~/js/searchEditAuthors.js"></script>